baseURL = "https://swieckikarmel.pl/"
languageCode = "pl-PL"
title = "Świecki Karmel Sopot"
theme = "ananke"
googleAnalytics = "UA-60769942-1"

[permalinks]
  posts = "/:slug"

[params]
  description = "Wspólnota Świeckiego Zakonu Karmelitów Bosych pw. św. Józefa Oblubieńca NMP w Sopocie"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
