baseURL = "https://swieckikarmel.pl/"
languageCode = "pl-PL"
title = "Świecki Karmel Sopot"
theme = "hyde"
staticDir = ["static"]
googleAnalytics = "UA-60769942-1"

[permalinks]
  posts = "/:slug"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  themeColor = "theme-base-0f"
  description = "Wspólnota Świeckiego Zakonu Karmelitów Bosych pw. św. Józefa Oblubieńca NMP w Sopocie"

[Menus]
  main = [
      {name = "Charyzmat", url = "/charyzmat/", weight = 1},
      {name = "Powołanie", url = "/powołanie/", weight = 2},
      {name = "Przyjęcie", url = "/przyjęcie/", weight = 3},
      {name = "Formacja", url = "/formacja/", weight = 4},
      {name = "Formuła przyrzeczeń", url = "/przyrzeczenia/", weight = 5},
      {name = "Diakonie", url = "/diakonie/", weight = 6},
      {name = "Relikwie wspólnotowe", url = "/relikwie-wspolnotowe/", weight = 7},
      {name = "Świadectwa", url = "/świadectwa/", weight = 8},
      {name = "Prośby o modlitwę", url = "mailto:modlitwa@swieckikarmel.pl?subject=Prośba o modlitwę", weight = 9},

      {name = "Blog", url = "http://swieckikarmelsopot.blogspot.com/", weight = 90},
      {name = "Kontakt", url = "/kontakt/", weight = 91},
      {name = "Linki", url = "/linki/", weight = 99},
  ]
